[package]
name = "integration_testing"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
anyhow = "1.0.28"
surf = "1.0.3"
async-std = {version = "1.5.0", features = ["attributes", "unstable"]}
assert_cmd = "1.0.1"
