[package]
name = "repository"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[lib]
name = "repository"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.30"
domain = { path = "../domain" }
db = { path = "../db" }
anyhow = "1.0.28"
futures-util = "0.3.4"
